version: '3.1'
services:
  development_env:
    build: .
    image: young_development_env
    container_name: works_env
    ports: 
      - 8000:8000
      - 8001:8001
      - 8002:8002
      - 8003:8003
      - 8004:8004
      - 8005:8005
    volumes:
      - ../:/home/dever/works
      - ./home/.zshenv:/home/dever/.zshenv
      - ./home/.tmux.conf:/home/dever/.tmux.conf
      - ./home/.gitconfig:/home/dever/.gitconfig
      - ./home/.git-credentials:/home/dever/.git-credentials
      - ./home/.config:/home/dever/.config
    extra_hosts:
      - "host.docker.internal:host-gateway"
