version: '3.1'
services:
  development_env:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_ID
        - GROUP_ID
        - USER_NAME
    image: young_development_env
    container_name: works_env
    volumes:
      - ../:/home/${USER_NAME}/works
      - ./home/.zshenv:/home/${USER_NAME}/.zshenv
      - ./home/.tmux.conf:/home/${USER_NAME}/.tmux.conf
      - ./home/.gitconfig:/home/${USER_NAME}/.gitconfig
      - ./home/.git-credentials:/home/${USER_NAME}/.git-credentials
      - ./home/.config:/home/${USER_NAME}/.config
    ports: 
      - 8000:8000
      - 8001:8001
      - 8002:8002
      - 8003:8003
      - 8004:8004
      - 8005:8005
    extra_hosts:
      - "host.docker.internal:host-gateway"
