version: '3.1'
services:
  development_env:
    build: .
    image: young_development_env
    container_name: works_env
    user: ${USER_ID}:${GROUP_ID}
    ports: 
      - 8000:8000
      - 8001:8001
      - 8002:8002
      - 8003:8003
      - 8004:8004
      - 8005:8005
    volumes:
      - ../:/root/works
      - ./home/.zshenv:/root/.zshenv
      - ./home/.tmux.conf:/root/.tmux.conf
      - ./home/.gitconfig:/root/.gitconfig
      - ./home/.git-credentials:/root/.git-credentials
      - ./home/.config:/root/.config
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
