
[cursor]
blink_interval = 750
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
dynamic_title = true
startup_mode = "Windowed"
title = "terminal"

[window.dimensions]
columns = 120
lines = 50

[window.padding]
x = 6
y = 6

[general]
live_config_reload = true
import = [
	"/home/tailor/.config/alacritty/alacritty-theme/themes/one_dark.toml",
	"/home/tailor/.config/alacritty/fonts.toml",
	"/home/tailor/.config/alacritty/keymaps.toml"
]

[terminal]
shell = "zsh"
